### PR TITLE
Overall cleanup and fixes.

### PR DESCRIPTION
**Pull request by sergiotapia**
This PR aims to improve the general code quality of the project. Byte-size commits as time allows, I'm really busy at [StackShare](https://stackshare.io/trending/tools)!

@tchoutri Did a fantastic job with the open PR (#52) and I'm going to bring in a lot of his suggested changes slowly as I understand what he's done in the individual commits. Unfortunately a lot of it is out of my league haha. Say thanks to him! 💪 

List of cleaned up and enabled parsers:

- Demonoid
- EZTV

### CODE REVIEW

**Comment by tchoutri** [comment]
Hi, first of all, thanks for your efforts!
Don't hesitate to ask me on Slack about the stuff you don't understand very well, I'd be glad to help you decipher my code :p
Théophile Choutri

https://www.linkedin.com/in/tchoutri

**Comment by sergiotapia** [comment]
- Guard clauses
- Better pattern matching
- New UI using Spectre CSS https://picturepan2.github.io/spectre/
- RSS feeds! Both newest and using search terms!

image


Updates coming along nicely. :)

**Comment by tchoutri** [comment]
@sergiotapia hi :) I understand you're very busy at work, so do you need me to work on a specific point?

**Comment by skwerlman** [comment]
Currently the Leetx crawler is erroring on every torrent with `Errors: magnet can't be blank`

**Comment by tchoutri** [comment]
Thanks the report :)
If the PR doesn't fix that I'll handle this one once it's merged.

**Comment by pahakalle** [comment]
Yeah didn't 1337x recently update their entire site or search function

**Comment by tchoutri** [comment]
Okay, I'm merging this PR since it will unlock many things for future development. :)

**Pull request merged**
