### PR TITLE
Separate fixture data from crawler's tests

### PR DESCRIPTION
**Pull request by coline-carle**
* Introduce Fixtures.load helper to load the fixture files
* Add the mix task fixtures.download "fixture_name" to maintain fixture
up to date

### CODE REVIEW

**Comment by wow-sweetlie** [comment]
The project is actually lacking of tests, I tested it for a few day and half crawler are not working.
The problem in parsing result from an external provider, is quite current and there is quite good solution like 
https://github.com/parroty/exvcr

I didn't want to add an extra dependancies, even for a few test so I implemented a mix task to update preconfigured fixtures. and a very simple helper to load them

I just updated the existing tests

1337x is actually down for me, so I kept the original

Also, sonner of later you will have complain if you link copyrated material in your sources files, I used research for work licensed under creative common, or under public domain.

**Comment by wow-sweetlie** [comment]
If you want more integration tests, bypass could provide a  more flexible solution than exvcr
https://github.com/PSPDFKit-labs/bypass

**Comment by swatgoss** [comment]
Is there a possibility to make some kind of versioned packages (like a separate github project maybe) that contains one or multiple crawlers ?

So you can update/patch/test a specific version and some external teams can make their own crawlers (private torrents sites ;) ) available to the public or to their users ...

**Comment by wow-sweetlie** [comment]
That's the purpose of the button fork, git is tailored for this kind of things, don't ask permission make the change you want.

**Pull request closed without merging**
