### PR TITLE
New year's resolutions 🎉

### PR DESCRIPTION
**Pull request by tchoutri**
### What's going on

Okay, so 2018 is approaching, and we've got a few goals to start this new year:

* [x] Migrating to Phoenix 1.3
* [x] Refreshing the dependencies, especially getting rid of HTTPoison in favour of Tesla
* [x] Update the code to eliminate deprecated functions
* [x] Write a `Crawler` behaviour so we make sure that all the crawlers share the same API
* [x] More documentation for new contributors
  * [ ] Writing new adapters for trackers

… and more to come as it is discussed.

### What's not going on

I also want to express what this pull request is **not** about

* It's not about adding new trackers or fixing the old ones (except if it prevents Magnetissimo from running well, and it _should_ be running well even if there's no internet…)
* It's not about Docker, Heroku, packaging for Debian…
* Putting an umbrella project is not one of the goals.

### CODE REVIEW

**Comment by sergiotapia** [comment]
Thanks for the help and joining as a contributor @tchoutri 🚀 

Once the new year starts I'll have more time to implement some of the ideas that I've had for Magnetissimo.

**Comment by pahakalle** [comment]
Transferring all or as many as possible of the crawlers to use rss.
Would be a good goal?

**Comment by sergiotapia** [comment]
Absolutely, we just need to find the right sources. I implemented rarbg using their API and it's infinitely easier and less error prone.

**Comment by tchoutri** [comment]
Open an issue for that kind of things, they will be useful for the future :)

**Comment by tchoutri** [comment]
Alright.

**Pull request merged**
