### PR TITLE
Fix compiler warning and other things

### PR DESCRIPTION
**Pull request by tchoutri**
This PR is a bit big, so here's what I did: 

* I fixed almost *all* compiler warnings, related to variable expansion to function (`initial_queue` → `initial_queue()`).
* In order to do so efficiently, I moved the `process` function implemented by each crawler to the `Helper` module…
* … And in order to keep it working, I changed its arity from `2` to `3`. Since it had to use a module-specific implementation of `torrent_links/1` and `torrent_information/1`, I went the functional path: those functions are now passed as a 3rd argument to the `process/3` function.
* I added function guards to `torrent_information` and `torrent_links`.
* Enabled a restart strategy for the crawlers (	e8135a2).
* Dirty-patched several Match Errors.
* I added a type (`Torrent.t`) for typespecs.

### CODE REVIEW

**Comment by sergiotapia** [comment]
Thanks @tchoutri I'll review this and run it locally before merging to double-check everything works. :)

**Comment by tchoutri** [comment]
Hahaha yeah sure! :p don't hesitate to reach me on Slack, I'm getting home soon

Le 31 janvier 2017 21:15:50 GMT+01:00, Sergio Tapia <notifications@github.com> a écrit :
>Thanks @tchoutri I'll review this and run it locally before merging to
>double-check everything works. :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sergiotapia/magnetissimo/pull/52#issuecomment-276478867

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tchoutri** [comment]
Hahaha yeah sure! :p don't hesitate to reach me on Slack, I'm getting home soon

Le 31 janvier 2017 21:15:50 GMT+01:00, Sergio Tapia <notifications@github.com> a écrit :
>Thanks @tchoutri I'll review this and run it locally before merging to
>double-check everything works. :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sergiotapia/magnetissimo/pull/52#issuecomment-276478867

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tchoutri** [comment]
Hahaha yeah sure! :p don't hesitate to reach me on Slack, I'm getting home soon

Le 31 janvier 2017 21:15:50 GMT+01:00, Sergio Tapia <notifications@github.com> a écrit :
>Thanks @tchoutri I'll review this and run it locally before merging to
>double-check everything works. :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sergiotapia/magnetissimo/pull/52#issuecomment-276478867

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.
-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tchoutri** [comment]
Hahaha yeah sure! :p don't hesitate to reach me on Slack, I'm getting home soon

Le 31 janvier 2017 21:15:50 GMT+01:00, Sergio Tapia <notifications@github.com> a écrit :
>Thanks @tchoutri I'll review this and run it locally before merging to
>double-check everything works. :)
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/sergiotapia/magnetissimo/pull/52#issuecomment-276478867

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by tchoutri** [comment]
@littlelampton what do you mean? =)

**Comment by scottharvey** [comment]
I was having issues with magnetissimo crashing all the time which made the application unusable (there are already issues filed). When using this PR I haven't had any issues and everything seems to work as expect. Great work @tchoutri 😀

**Comment by tchoutri** [comment]
thankis @scottharvey :) however I may not be able to work more on it these days, because I think most of the sites ended up by banning my IP (so I guess it's a good incentive to add a more reliable timing strategy so we don't get banned.)

**Comment by scottharvey** [comment]
@tchoutri Can't you use a VPN to fix that?

**Comment by tchoutri** [comment]
@scottharvey yeah I got a machine or two that could do the job as well :)

**Comment by tchoutri** [comment]
(unrelated, but if someone manages to use Dialyzer on the project, without a segfault, I'd be glad to know  how :p)

**Comment by sergiotapia** [comment]
@tchoutri Hey I've been swamped with work at StackShare, but I'll set aside some time this weekend to ship this for real! Thanks for all your help and contributions, I appreciate it. 😄 

I need to ship some other stuff I've been working on to for Magnetissimo.

**Comment by tchoutri** [comment]
@sergiotapia don't worry, I just hope you're doing good :)

**Pull request closed without merging**
