### PR TITLE
Fixing the downloader helper

### PR DESCRIPTION
**Pull request by tchoutri**
This fix adds 2 features:

* The downloader checks the content type of the pages, and 
* The downloader handles redirections. I haven't fully tested yet so 2 solutions live next to each other for the moment.

### CODE REVIEW

**Comment by sergiotapia** [comment]
This looks great @tchoutri thanks for the improvements!

**Comment by sergiotapia** [comment]
```
→ mix phoenix.server
Compiling 21 files (.ex)

== Compilation error on file lib/crawler/helper.ex ==
** (SyntaxError) lib/crawler/helper.ex:50: syntax error before: do
    (elixir) lib/kernel/parallel_compiler.ex:117: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/1
```

**Comment by sergiotapia** [comment]
@tchoutri I get the error above if I try to run the project. I don't quite understand the `with` statement yet so I can't fix it myself. Can you take a look and let me know? I'll merge once it's working again :D

**Comment by tchoutri** [comment]
Fixed :)

**Pull request merged**
