### PR TITLE
Change outbound_url to :text

### LINKED ISSUE #100: Leetx crawler crash on long URL
Given a very long URL (longer than 255 chars), the Leetx crawler crashes with:

```
[error] GenServer Magnetissimo.Crawler.Leetx terminating
** (Postgrex.Error) ERROR 22001 (string_data_right_truncation): value too long for type character varying(255)
    (ecto) lib/ecto/adapters/sql.ex:554: Ecto.Adapters.SQL.struct/8
    (ecto) lib/ecto/repo/schema.ex:547: Ecto.Repo.Schema.apply/4
    (ecto) lib/ecto/repo/schema.ex:213: anonymous fn/14 in Ecto.Repo.Schema.do_insert/4
    (magnetissimo) lib/magnetissimo/contents.ex:9: Magnetissimo.Contents.save_torrent/1
    (magnetissimo) lib/magnetissimo/crawler/leetx.ex:83: Magnetissimo.Crawler.Leetx.process/2
    (magnetissimo) lib/magnetissimo/crawler/leetx.ex:50: Magnetissimo.Crawler.Leetx.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: :work
```

I don't know if there's a clean way of solving this other than changing the URL column to `:text` because Leetx won't accept partial or missing slugs, even though they also have unique ids for torrents.

### PR DESCRIPTION
**Pull request by skwerlman**
Fixes #100

### CODE REVIEW

**Comment by skwerlman** [comment]
The reason I added a new migration was so I didn't need to nuke my database, but i guess we're still early enough that backwards-compat isn't really a goal. I'll update the PR in a moment

**Comment by tchoutri** [comment]
@skwerlman oh yeah I reset my own database, like, 4 times a week? At least after every pull request :)
We're super early and I don't see us having to worry about backward compatibility before a few months.

**Comment by skwerlman** [comment]
PR should be good to go :)

**Comment by tchoutri** [comment]
Yeah, it's quite convenient actually, and having visual feedback is quite nice

**Pull request merged**
