### PR TITLE
Add Rarbg.to crawler to the project.

### PR DESCRIPTION
**Pull request by sergiotapia**
This adds Rarbg support for Magnetissimo. They have some sort of "threat_defence.php" system in place that redirects when you visit a torrent page.

As soon as that's sorted out the parsers can work fine. 😄

---
This change is [Reviewable](https://reviewable.io/reviews/sergiotapia/magnetissimo/45)

### CODE REVIEW

**Comment by chopraaa** [comment]
Thread defense is against bad traffic. Try using another host.

**Comment by sergiotapia** [comment]
I'm running the project locally, not even running on a VPS.

**Comment by chopraaa** [comment]
Your network must be blacklisted on Cloudflare then. ¯\_(ツ)_/¯ 
Yes, RARBG uses Cloudflare.

**Comment by rarbg** [comment]
Every user using your app  will be permanently banned from using our site because of your integration. We have automated protections that prevent what you are trying to do the way you are trying to do it
Please integrate our api 
docs https://torrentapi.org/apidocs_v2.txt
github https://github.com/rarbg/torrentapi

**Comment by sergiotapia** [comment]
I didn't know you guys had an API, even better! Thanks for the heads up.

**Comment by sergiotapia** [comment]
https://torrentapi.org/pubapi_v2.php?mode=list&token=TOKEN&limit=100

**Comment by nvanmeurs** [comment]
Will this still be implemented sometime?

**Comment by sergiotapia** [comment]
Yes! I've been swamped at work and haven't had a chance to do anything related to Magnetissimo in a month.

**Comment by nvanmeurs** [comment]
It's cool, I'm currently learning Elixir. Looking forward to play around with it :)

**Comment by pahakalle** [comment]
Rarbg seems to have an rss feed too https://rarbg.is/rss
Will using it perma ban tough?

**Comment by tchoutri** [comment]
@rarbg Hi! Do you think it would be possible to add the magnet link and the number of seeders/leechers in your RSS feed? That would greatly help us and we won't need to parse every page listed, just get what we need from the RSS feed. 
Thanks for your participation.

**Comment by rarbg** [comment]
@tchoutri

We can add that but it wont be realtime. There will be probably some if 
not a big (30min+ delay) on seeders/leechers count. is that ok ?

**Comment by tchoutri** [comment]
@rarbg On our side we often wait for 30 minutes before crawling the feeds again, so it can fill up again.
We don't "update" the seeders/leechers count either, so it can be 0.
Can't you publish your feeds only when the S/L count is obtained?

**Comment by rarbg** [comment]
@tchoutri you should be using the API for any advanced features...

**Comment by tchoutri** [comment]
@rarbg I would love to but this happens: 
capture du 2018-01-09 17-19-13

Moreover, [rarbg/torrentapi](https://github.com/rarbg/torrentapi) doesn't exist anymore :/

**Comment by rarbg** [comment]
@tchoutri 
We are just having some issues with the API servers. Nothing major. Should be fixed within 12-24h

And about the project - its private i just sent you an invite

**Comment by tchoutri** [comment]
Just saw that, thank you very much for supporting our work :)

**Comment by tchoutri** [comment]
@rarbg I'm getting 404s when I try to request a token (`https://torrentapi.org/pubapi_v2.php&get_token=get_token` as specified). Is there some status page or alert system when the API doesn't work? Or perhaps I could try and write an alternative implementation of the endpoint in Elixir ;)

**Comment by tchoutri** [comment]
(or do you folks have a chatroom I could join?)

**Comment by rarbg** [comment]
@tchoutri 
GET requests on the web start with ? . You used &

**Comment by tchoutri** [comment]
@rarbg oh yeah of course, perhaps I need to sleep more. Thanks :)

**Comment by sergiotapia** [comment]
@rarbg Can you send me an invite to the torrentapi project as well? I'm hoping back on this workload. Thank you!

**Pull request closed without merging**
